### ISSUE TITLE
Upgrade to ArcGIS 10.5.1

### ISSUE THREAD

**Issue by ranga-tolapi** [Esri/rabbitmq-for-geoevent#3]
Any plans to upgrade this to support ArcGIS 10.5.1?

**Comment by LordMike** [comment]
Seems to work with 10.6.0 now.

**Comment by hanoch** [comment]
Unless something has changed in regards to RabbitMQ, the same version of the transport should work with the 10.7.x releases. Custom components don't have to match version numbers unless there was a breaking change that required code updates. If you find it's not working for you, please detail your workflow and we can try to investigate what's causing that issue.
