### ISSUE TITLE
Upgrade to ArcGIS 10.6.1

### ISSUE THREAD

**Issue by LuisRguezEsriSpain** [Esri/rabbitmq-for-geoevent#5]
Any plans to upgrade this to support ArcGIS 10.6.1?

Does "rabbitmq-for-geoevent" 1.6.0 work on GeoEvent 10.6.1?

**Comment by gtieman** [comment]
Hi @LuisRguezEsriSpain, yes, the 10.6.0 version of the RabbitMQ Connector works on GeoEvent Server 10.6.1 and no upgrade is necessary.
