### ISSUE TITLE
Upgrade to ArcGIS 10.7

### ISSUE THREAD

**Issue by olazt** [Esri/rabbitmq-for-geoevent#7]
Do you have any plans to upgrade this to support ArcGIS 10.7/ 10.7.1?

**Comment by jhjoyner1** [comment]
@olazt Unless something has changed in regards to RabbitMQ, the same version of the transport should work with the 10.7.x releases. Custom components don't have to match version numbers unless there was a breaking change that required code updates. If you find it's not working for you, please detail your workflow and we can try to investigate what's causing that issue.

**Comment by olazt** [comment]
Josh, thank you very much for response! I will test it.
